import "package:flutter/material.dart";
import "package:flutter_ai_app/apis/apis.dart";
import "package:flutter_ai_app/models/message.dart";
import "package:get/get.dart";

import "../helper/mydialog.dart";

class TranslatorController extends GetxController{
  static bool isFirstTimeAnimating = true;
  final textController = TextEditingController();
  final resultController = TextEditingController();
  var from = "".obs;
  var to = "".obs;
  final lang = const [
    "Afar",
    "Abkhazian",
    "Avestan",
    "Afrikaans",
    "Akan",
    "Amharic",
    "Aragonese",
    "Arabic",
    "Assamese",
    "Avaric",
    "Aymara",
    "Azerbaijani",
    "Bashkir",
    "Belarusian",
    "Bulgarian",
    "Bihari languages",
    "Bislama",
    "Bambara",
    "Bengali",
    "Tibetan",
    "Breton",
    "Bosnian",
    "Catalan",
    "Chechen",
    "Chamorro",
    "Corsican",
    "Cree",
    "Czech",
    "Church Slavic",
    "Chuvash",
    "Welsh",
    "Danish",
    "German",
    "Maldivian",
    "Dzongkha",
    "Ewe",
    "Greek",
    "English",
    "Esperanto",
    "Spanish",
    "Estonian",
    "Basque",
    "Persian",
    "Fulah",
    "Finnish",
    "Fijian",
    "Faroese",
    "French",
    "Western Frisian",
    "Irish",
    "Gaelic",
    "Galician",
    "Guarani",
    "Gujarati",
    "Manx",
    "Hausa",
    "Hebrew",
    "Hindi",
    "Hiri Motu",
    "Croatian",
    "Haitian",
    "Hungarian",
    "Armenian",
    "Herero",
    "Interlingua",
    "Indonesian",
    "Interlingue",
    "Igbo",
    "Sichuan Yi",
    "Inupiaq",
    "Ido",
    "Icelandic",
    "Italian",
    "Inuktitut",
    "Japanese",
    "Javanese",
    "Georgian",
    "Kongo",
    "Kikuyu",
    "Kuanyama",
    "Kazakh",
    "Kalaallisut",
    "Central Khmer",
    "Kannada",
    "Korean",
    "Kanuri",
    "Kashmiri",
    "Kurdish",
    "Komi",
    "Cornish",
    "Kirghiz",
    "Latin",
    "Luxembourgish",
    "Ganda",
    "Limburgan",
    "Lingala",
    "Lao",
    "Lithuanian",
    "Luba-Katanga",
    "Latvian",
    "Malagasy",
    "Marshallese",
    "Maori",
    "Macedonian",
    "Malayalam",
    "Mongolian",
    "Marathi",
    "Malay",
    "Maltese",
    "Burmese",
    "Nauru",
    "Norwegian",
    "North Ndebele",
    "Nepali",
     "Ndonga",
     "Dutch",
     "South Ndebele",
     "Navajo",
     "Chichewa",
     "Occitan",
     "Ojibwa",
     "Oromo",
     "Oriya",
     "Ossetic",
     "Panjabi",
     "Pali",
     "Polish",
     "Pushto",
     "Portuguese",
     "Quechua",
     "Romansh",
     "Rundi",
     "Romanian",
     "Russian",
     "Kinyarwanda",
     "Sanskrit",
     "Sardinian",
     "Sindhi",
     "Northern Sami",
     "Sango",
     "Sinhala",
     "Slovak",
     "Slovenian",
     "Samoan",
     "Shona",
     "Somali",
     "Albanian",
     "Serbian",
     "Swati",
     "Sotho, Southern",
     "Sundanese",
     "Swedish",
     "Swahili",
     "Tamil",
     "Telugu",
     "Tajik",
     "Thai",
     "Tigrinya",
     "Turkmen",
     "Tagalog",
     "Tswana",
     "Tonga",
     "Turkish",
     "Tsonga",
     "Tatar",
     "Twi",
     "Tahitian",
     "Uighur",
     "Ukrainian",
     "Urdu",
     "Uzbek",
     "Venda",
     "Vietnamese",
     "Volapük",
     "Walloon",
     "Wolof",
     "Xhosa",
     "Yiddish",
     "Yoruba",
     "Zhuang",
     "Chinese",
     "Zulu"
   ];
  Future<String> translateText(String question, String to) async{
    String translation = "";
    if(textController.text.trim().isNotEmpty){
     translation = await APIs.getTranslation(question, to);
     print("translation result: ${translation}");
      textController.text = translation;
    }
    else{
      MyDialog.showInfoDialog("Please ask something");
    }
    return translation;
  }

}